Atoms-editbutton
U03KTGYJS1E/mion-frontend-basic-2022-todoapp pull request #2
Opened 2024-01-03 04:47 UTC by U03KTGYJS1E

2024-02-09 04:19 UTC, MinamiHotta reviewed
おそらくCheckboxも紛れ込んでしまっていたので、PRを分けるようお願いします。
ただ、良い機会だったので、同時にレビューしてしまいました。

2024-02-09 04:19 UTC, MinamiHotta commented on src/components/Atoms/Checkbox/index.jsx
> +import TEXT from "../../../variables/texts";
こちら使用していないので記述しなくてよいです

2024-02-09 04:19 UTC, MinamiHotta commented on src/components/Atoms/EditButton/index.jsx
> +const Button = styled.button`
自分で作り出しているものなので、一般的なボタンとすみわけするために
`Button`ではなく`Styled Button`の方がよいです

2024-02-09 04:19 UTC, MinamiHotta commented on src/components/Atoms/EditButton/index.jsx
> +  transition: 0.2s;
`0.2s ease`でお願いします

2024-02-09 04:19 UTC, MinamiHotta commented on src/components/Atoms/EditButton/index.jsx
> +const Button = styled.button`
やや変化が見えにくいのですが、`outline:none`も加えてください

2024-02-09 04:19 UTC, MinamiHotta commented on src/components/Atoms/Checkbox/index.jsx
> +const Button = styled.button`
これだとすべてのPRをコンパイルした際に、Buttonと名の付く他のパーツにもスタイルが当たってしまう可能性があるので、`StyledCheckbox`などと他の変数名にしましょう。

2024-02-09 04:19 UTC, MinamiHotta commented on src/components/Atoms/Checkbox/index.jsx
> +export default Checkbox;
`export const (変数名)=>{}` もしくは `const (変数名)=>{} export default (変数名)`のいずれかであればよいので、今回の記述だと重複してexportしてしまっている状態です。
どちらかの記述にしましょう。おそらく他のPRで前者にしていたはず。

2024-02-09 04:19 UTC, MinamiHotta commented on src/components/Atoms/Checkbox/index.jsx
> +    <Button onClick={props.onClick}>
stories.jsxではここを`onclick: () => console.log("clicked"),`としているので、対応できておらず、storybookのConsoleでもonClickがでてきていない状況です。

提案としては
1. `props`と書いている部分を`onClick`だけにする
2. stories.jsxの方を`onclick`という小文字ではなく`onClick`とし単語のつなぎ目が分かりやすくなるよう小文字大文字を使い分ける
です。

修正したら、storybookのConsoleでしっかり出現するか確認してみてください。

2024-02-09 09:35 UTC, MinamiHotta approved these changes

2024-02-09 09:35 UTC, MinamiHotta commented on src/components/Atoms/EditButton/index.jsx
> +export default EditButton;
> `export const (変数名)=>{} `もしくは `const (変数名)=>{} export default (変数名)`のいずれかであればよいので、今回の記述だと重複してexportしてしまっている状態です。
どちらかの記述にしましょう。おそらく他のPRで前者にしていたはず。

Checkboxの方で指摘した事項ですが、こちらでも修正お願いします。
※[参考](https://qiita.com/toknr/items/9b32ce5a9f61af3bb6b4)

2024-02-10 15:05 UTC, higashiji2000 requested changes
Checkbox関連のファイルを削除して、
それをコミットしてからマージしましょう!

2024-02-10 15:05 UTC, higashiji2000 commented on src/components/Atoms/Checkbox/index.jsx
> +const Button = styled.button`
@U03KTGYJS1E cc @MinamiHotta 
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-2022-todoapp/assets/83479175/93c5b669-f4a2-4bf6-8e85-d71301d95335)

styled-components はコンポーネントごとにランダムなクラス名を割り当てるので、cssのクラス名とは違いコンポーネント名の被りを気にしないで大丈夫です！

2024-02-15 23:34 UTC, merged