Morecules-Task
U03KTGYJS1E/mion-frontend-basic-2022-todoapp pull request #6
Opened 2024-03-26 09:14 UTC by U03KTGYJS1E

2024-03-28 04:47 UTC, MinamiHotta commented on src/components/Molecules/task/index.stories.jsx
> +};
エラー文をChatGPTに投げてみたところ

> Reactが期待していた値がundefinedであることを示している

とのことだったので、受け渡しているpropsを再度確認し、抜け漏れがないか確認するとよさそうです。
例えば、`defaultEditing`の値を渡してやるとどうでしょう...？（渡されなかった場合の初期値の設定をしてくれているので、関係ない気もしますが...）
```suggestion
export const Default = {
  args: {
    taskName: "taskname",
    onTaskComplete: () => {
      console.log("task completed");
    },
　defaultEditing:  false
    onTaskNameChange: () => {
      console.log("taskname changed");
    },
  },
};
```

2024-03-28 04:48 UTC, MinamiHotta commented
ちなみに、`Task`の中のコードは全く問題なさそうでした...！
よくかけていると思います◎

2024-03-28 04:57 UTC, MinamiHotta commented on src/components/Molecules/task/index.jsx
> +import Input from "../../Atoms/Input/index";
```suggestion
import Checkbox from "../../Atoms/Checkbox";
import EditButton from "../../Atoms/EditButton";
import Input from "../../Atoms/Input";
```
もしくは、`../../Atoms/Checkbox/index`というファイルは存在しない&`index.js`だけでなくCheckbox自体をimportしたいので、このように変更するとかですかね...？

2024-03-28 08:05 UTC, U03KTGYJS1E commented on src/components/Molecules/task/index.stories.jsx
> +};
なぜかは分からないのですが、7,8行目の間に空行を入れるとうまくいきました！
importも試してみたのですが、それだとやはりインポートできなかったのでpropだけが原因だったようです。
コメントくださりありがとうございました。

2024-03-29 09:08 UTC, MinamiHotta commented on src/components/Molecules/task/index.jsx
> +  function onEditButtonClick() {
アロー関数で`const 関数名=(props)=>{}`とするのと、functionを用いて`function 関数名(props){}`とするのが混在するとコードが見にくいのでどちらかに統一すると良いと思います。これまでは前者で定義していたので、前者に統一した方がよさそうです。

2024-03-29 09:34 UTC, MinamiHotta commented on src/components/Molecules/task/index.stories.jsx
> +};
この時のエラー文はこちらでした

> Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

2024-03-30 06:18 UTC, MinamiHotta commented on src/components/Molecules/task/index.jsx
> +  taskName = "taskname",
この初期値は`taskName = ""`の方がいいと思います
（何もtextが与えられないとき勝手にtasknameと入ってしまいそうな気がするので）
↑
試しに，鉛筆マークを押して現状書かれているtasknameという文字を消してみてください
（消したはずなのにtasknameと現れるはずです）

2024-03-30 06:18 UTC, MinamiHotta commented on src/components/Molecules/task/index.jsx
> +const StyledTaskName = styled.div`
入力中の文字のフォント設定をお願いします

2024-03-30 06:18 UTC, MinamiHotta commented on src/components/Molecules/task/index.stories.jsx
> +    },
> タスク名の編集が完了すると、Console に"taskname changed: <変更後のタスク名>"と表示される。

教材にこのように記載があるので，propsの受け渡しをしてこちらを再現してください
例：`宿題`と入力されたとき，consoleには`taskname changed: 宿題`と現れるように

2024-03-30 15:01 UTC, U03KTGYJS1E commented on src/components/Molecules/task/index.jsx
> +import { Input } from "../../Atoms/Input/index";
[エラー]
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-2022-todoapp/assets/110463648/cbfdcd1e-ec77-4e8f-b78f-fa5984e453c0)

[原因]
・名前付きでimportする場合はimport {名前}と書くべきところ、{}を付けていなかった
・storybookやchatGPTでエラー発生場所としてpropsが指摘されていたため、原因をそこだと思いこみ修正が遅れた。ネットでも検索をかけるべきだった。
　　
[参考]https://ja.react.dev/learn/importing-and-exporting-components

2024-03-31 08:49 UTC, higashiji2000 requested changes
長いテキストが入力されたときの省略が不十分なので、こちら修正お願いします。

お手本：
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-2022-todoapp/assets/83479175/fe2b7173-8f94-4ef0-be7c-321b01f370eb)

現状：
![image](https://github.com/U03KTGYJS1E/mion-frontend-basic-2022-todoapp/assets/83479175/b0c8ed8c-d925-4eed-89d3-655dffe9cad8)

お手本Storybook：https://shinonome.io/frontend-basic-todoapp-storybook/?path=/story/molecules-task--default

2024-04-02 15:22 UTC, higashiji2000 requested changes
このように修正すると、お手本通り省略されるようになると思います。
試してみてください 🏛️

2024-04-02 15:22 UTC, higashiji2000 commented on src/components/Molecules/task/index.jsx
> +`;
```suggestion
const StyledNameAndButtonWrapper = styled.div`
  display: flex;
  align-items: center;
  flex: auto;
  overflow: hidden;
`;
```

2024-04-02 15:22 UTC, higashiji2000 commented on src/components/Molecules/task/index.jsx
> +`;
```suggestion
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
`;
```

2024-04-04 14:51 UTC, higashiji2000 approved these changes
LGTM 🧇

2024-04-05 01:52 UTC, merged